project:
  type: website
  render: 
    - index.qmd
    - home.qmd
    - ep_1.qmd
    - ep_2.qmd
    - ep_3.qmd
    - ep_4.qmd
    - ep_5.qmd
    - ep_6.qmd
    - ep_7.qmd
    

website:
  title: "Il Diario di Tarcisio, Esploratore di Rovigo"
  page-navigation: true
  sidebar:
    style: "floating"
    search: false
    contents:
      - text: "Introduzione"
        href: home.qmd
      - text: "Prima Leggenda"
        href: ep_1.qmd
      - text: "Seconda Leggenda"
        href: ep_2.qmd
      - text: "Terza Leggenda"
        href: ep_3.qmd
      - text: "Quarta Leggenda"
        href: ep_4.qmd
      - text: "Quinta Leggenda"
        href: ep_5.qmd
      - text: "Sesta Leggenda"
        href: ep_6.qmd
      - text: "Settimana Leggenda"
        href: ep_7.qmd

format:
  html:
    theme: default
    css: custom.css

include-after-body:
  text: |
    <script type="application/javascript" src="custom.js"></script>
    <link rel="stylesheet" href="custom.css" />