project:
  type: website
  output-dir: docs

website:
  title: "Il Diario di Tarcisio, Esploratore di Rovigo"
  sidebar:
    style: "floating"
    contents:
      - home.qmd
      - leggende/ep_1.qmd

format:
  html:
    theme: default
    css: custom.css
    js: custom.js