project:
  type: website
  output-dir: docs

website:
  title: "Le leggende di Rovigo"
  navbar:
    left:
      - text: "Trama"
        href: home.qmd

format:
  html:
    theme: default
    css: styles/custom.css
    js: scripts/custom.js
