project:
  type: website
  output-dir: docs

website:
  title: "Le Cronache di Rovigo"
  
sidebar:
  style: "floating"
  search: true
  contents:
    - home.qmd
    - ep_1.qmd

format:
  html:
    theme: default
    css: custom.css
    js: custom.js
